# creating first deep learning neural network model in Python using Keras

In [ ]:
!pip install keras

In [51]:
import numpy as np

In [52]:
from numpy import loadtxt

In [53]:
from keras.layers import Dense

In [54]:
from keras.models import Sequential

In [55]:
#load dataset
dataset=loadtxt('/home/himalayan/Downloads/indians-diabetes.data.csv',delimiter=',')

This is a standard machine learning dataset from the UCI Machine Learning repository.
It describes patient medical record data for Pima Indians and whether they had an onset of diabetes within five years.

In [56]:
#visualizing our dataset
import pandas as pd
df=pd.read_csv('/home/himalayan/Downloads/indians-diabetes.data.csv')
df

6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
5     3   78  50  32   88  31.0  0.248  26  1
6    10  115   0   0    0  35.3  0.134  29  0
7     2  197  70  45  543  30.5  0.158  53  1
8     8  125  96   0    0   0.0  0.232  54  1
9     4  110  92   0    0  37.6  0.191  30  0
10   10  168  74   0    0  38.0  0.537  34  1
11   10  139  80   0    0  27.1  1.441  57  0
12    1  189  60  23  846  30.1  0.398  59  1
13    5  166  72  19  175  25.8  0.587  51  1
14    7  100   0   0    0  30.0  0.484  32  1
15    0  118  84  47  230  45.8  0.551  31  1
16    7  107  74   0    0  29.6  0.254  31  1
17    1  103  30  38   83  43.3  0.183  33  0
18    1  115  70  30   96  34.6  0.529  32  1
19    3  126  88  41  235  39.3  0.704  27  0
20    8   99  84   0    0  35.4  0.388  50  0
21    7  196  90   0    0  39.8  0.451  41  1
22    9  119  80  35    0  29.0  0.263  29  1
23   11  143  94  33  146  36.6  0.254  51  1
24   10  125  70  26  115  31.1  0.205  41  1
25    7  147  76   0    0  39.4  0.257  43  1
26    1   97  66  15  140  23.2  0.487  22  0
27   13  145  82  19  110  22.2  0.245  57  0
28    5  117  92   0    0  34.1  0.337  38  0
29    5  109  75  26    0  36.0  0.546  60  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
737   2   99  60  17  160  36.6  0.453  21  0
738   1  102  74   0    0  39.5  0.293  42  1
739  11  120  80  37  150  42.3  0.785  48  1
740   3  102  44  20   94  30.8  0.400  26  0
741   1  109  58  18  116  28.5  0.219  22  0
742   9  140  94   0    0  32.7  0.734  45  1
743  13  153  88  37  140  40.6  1.174  39  0
744  12  100  84  33  105  30.0  0.488  46  0
745   1  147  94  41    0  49.3  0.358  27  1
746   1   81  74  41   57  46.3  1.096  32  0
747   3  187  70  22  200  36.4  0.408  36  1
748   6  162  62   0    0  24.3  0.178  50  1
749   4  136  70   0    0  31.2  1.182  22  1
750   1  121  78  39   74  39.0  0.261  28  0
751   3  108  62  24    0  26.0  0.223  25  0
752   0  181  88  44  510  43.3  0.222  26  1
753   8  154  78  32    0  32.4  0.443  45  1
754   1  128  88  39  110  36.5  1.057  37  1
755   7  137  90  41    0  32.0  0.391  39  0
756   0  123  72   0    0  36.3  0.258  52  1
757   1  106  76   0    0  37.5  0.197  26  0
758   6  190  92   0    0  35.5  0.278  66  1
759   2   88  58  26   16  28.4  0.766  22  0
760   9  170  74  31    0  44.0  0.403  43  1
761   9   89  62   0    0  22.5  0.142  33  0
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

Input Variables (X):

    1) Number of times pregnant
    2) Plasma glucose concentration a 2 hours in an oral glucose tolerance test
    3) Diastolic blood pressure (mm Hg)
    4) Triceps skin fold thickness (mm)
    5) 2-Hour serum insulin (mu U/ml)
    6) Body mass index (weight in kg/(height in m)^2)
    7) Diabetes pedigree function
    8) Age (years)

Output Variables (y):

    Class variable (0 or 1)


In [57]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [58]:
#input 8 columns from 0-7 (i.e.indices sliced by 0:8)
X=dataset[:,0:8]
#output 9th column or 9th variable (i.e. index 8)
Y=dataset[:,8]

In [59]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [60]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [61]:
#defining models
model=Sequential()
    #FIRST HIDDEN LAYER HAS 12 NODES WITH RELU ACTIVATION FXN AND MODEL DATA WITH 8 FEATURES/VARIABLES
model.add(Dense(12,input_dim=8,activation='relu'))
    #SECOND HIDDEN LAYER HAS 8 NODES WITH RELU ACTIVATION FXN
model.add(Dense(8,activation='relu'))
    #OUTPUT LAYER HAS 1 NODES WITH SIGMOID ACTIVATION FXN (since sigmoid function gives binary output, which we are looking for)
model.add(Dense(1,activation='sigmoid'))

In [62]:
#compiling the model
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [63]:
#fitting the keras model on the dataset
    #Epoch: One pass through all of the rows in the training dataset
    #Batch: One or more samples considered by the model within an epoch before weights are updated
model.fit(X,Y,epochs=100,batch_size=5)

Epoch 1/100
768/768 [==============================] - 1s 964us/step - loss: 3.4514 - accuracy: 0.5039
Epoch 2/100
768/768 [==============================] - 0s 434us/step - loss: 1.2648 - accuracy: 0.5651
Epoch 3/100
768/768 [==============================] - 0s 441us/step - loss: 0.8765 - accuracy: 0.5885
Epoch 4/100
768/768 [==============================] - 0s 440us/step - loss: 0.7637 - accuracy: 0.6224
Epoch 5/100
768/768 [==============================] - 0s 445us/step - loss: 0.7697 - accuracy: 0.6263
Epoch 6/100
768/768 [==============================] - 0s 528us/step - loss: 0.6917 - accuracy: 0.6602
Epoch 7/100
768/768 [==============================] - 0s 446us/step - loss: 0.6978 - accuracy: 0.6549
Epoch 8/100
768/768 [==============================] - 0s 551us/step - loss: 0.6409 - accuracy: 0.6875
Epoch 9/100
768/768 [==============================] - 0s 529us/step - loss: 0.6773 - accuracy: 0.6784
Epoch 10/100
768/768 [==============================] - 0s 556us/step - l

768/768 [==============================] - 0s 441us/step - loss: 0.5066 - accuracy: 0.7474
Epoch 80/100
768/768 [==============================] - 0s 430us/step - loss: 0.5126 - accuracy: 0.7474
Epoch 81/100
768/768 [==============================] - 0s 446us/step - loss: 0.4918 - accuracy: 0.7552
Epoch 82/100
768/768 [==============================] - 0s 469us/step - loss: 0.5293 - accuracy: 0.7461
Epoch 83/100
768/768 [==============================] - 0s 440us/step - loss: 0.5229 - accuracy: 0.7435
Epoch 84/100
768/768 [==============================] - 0s 439us/step - loss: 0.5124 - accuracy: 0.7292
Epoch 85/100
768/768 [==============================] - 0s 434us/step - loss: 0.5073 - accuracy: 0.7604
Epoch 86/100
768/768 [==============================] - 0s 429us/step - loss: 0.4948 - accuracy: 0.7539
Epoch 87/100
768/768 [==============================] - 0s 445us/step - loss: 0.4929 - accuracy: 0.7643
Epoch 88/100
768/768 [==============================] - 0s 417us/step - loss:

In [64]:
#Evaluating the model
accuracy=model.evaluate(X,Y)

768/768 [==============================] - 0s 67us/step


In [65]:
accuracy_=accuracy*100
print(accuracy_)

[0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 0.47873066117366153, 0.75, 

First values are losses and the second are accuracies

In [66]:
#make prediction
predictions=model.predict(X)

In [67]:
predictions 

array([[4.78773952e-01],
       [1.50074363e-01],
       [9.44171429e-01],
       [8.63943100e-02],
       [6.14131331e-01],
       [2.64531910e-01],
       [1.41120434e-01],
       [7.26623654e-01],
       [8.00196111e-01],
       [2.18167841e-01],
       [1.22427911e-01],
       [7.54333258e-01],
       [3.05543482e-01],
       [7.19527721e-01],
       [6.08453155e-01],
       [2.20649570e-01],
       [2.04024017e-01],
       [3.27941060e-01],
       [1.00495815e-01],
       [1.63129449e-01],
       [2.08296210e-01],
       [1.16218984e-01],
       [7.21566200e-01],
       [2.49824762e-01],
       [4.61400390e-01],
       [4.00745064e-01],
       [5.65657139e-01],
       [8.12744200e-02],
       [1.30698383e-02],
       [1.95022106e-01],
       [2.73452282e-01],
       [4.08561289e-01],
       [5.69362938e-02],
       [5.49539924e-03],
       [3.27586949e-01],
       [3.30264181e-01],
       [5.56398749e-01],
       [2.81686783e-01],
       [1.82510406e-01],
       [4.84321922e-01],


Since sigmoid activation has been used here the prediction 
values are obtained between 0 and 1

In [68]:
# make class predictions with the model
predictions_class = model.predict_classes(X)

In [69]:
predictions_class

array([[0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

This gives the binary output for each of the content our dataset